spring.application.name=SpringSecurityApp

# Database configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/securitydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

# Security Config
#spring.security.user.name=santiago
#spring.security.user.password=1234

# los nombres de los security de aqui son inventados solo son para mapear los valores
security.jwt.key.private=e75cb76aee33c5f60afe652d2d255307cdc518163106e2c5105d3cc986275027
security.jwt.user.generator=AUTH0JWT-BACKEND