spring.application.name=SpringSecurityApp

# Database configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/securitydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

# Security Config
#spring.security.user.name=santiago
#spring.security.user.password=1234

# los nombres de los security de aqui son inventados solo son para mapear los valores
security.jwt.key.private=465d9ad5d5528ebe287b5dce4fb51620833d09b290e49ddcc70ca6c4a0aea01b
security.jwt.user.generator=AUTH0JWT-BACKEND